### ISSUE TITLE
API choices

### ISSUE THREAD

**Issue by jonathanasquier** [dobobaie/redis-expiry#15]
```
rexp.on("myKeyByTimeout", (value, key) => {
  // value === "myValue"
});
```

set and get are (key, value), but the event callback is (value, key). Why?

**Comment by dobobaie** [comment]
In this situation, `key` is a little bit useless because you know what is your key.  
So the first thing that you want to retrieve is your value.
BUT when the `regex` feature will be deployed THEN retrieve the `key` will be more interesting, but I think always in second time.
About `set` and `get`, the most important thing in this case is the `key` then the `value`.
  
Does that make sense to you?

**Comment by jonathanasquier** [comment]
Yes, and as long as it's well documented it's good for me!
